FROM harbor.cloud.infn.it/datacloud-templates/cygno-lab:cygno-minio-rgw
ARG TAG
# FROM gmazzitelli/${TAG}
ARG CLIB
RUN pip3 install --no-cache-dir -U git+https://github.com/CYGNUS-RD/cygno.git@${CLIB}
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt
#
# RUN yum install -y https://research.cs.wisc.edu/htcondor/repo/10.x/el7/x86_64/release/htcondor-release-10.x-1.el7.noarch.rpm
# RUN yum install -y condor
# RUN yum install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
# RUN yum install -y cvmfs
# RUN mkdir -p /cvmfs/sft.cern.ch
# RUN echo -e 'CVMFS_HTTP_PROXY="auto;DIRECT"\nCVMFS_PAC_URLS="http://cernvm-wpad.fnal.gov/wpad.dat;http://grid-wpad/wpad.dat;http://wpad/wpad.dat;http://cernvm-wpad.fnal.gov/wpad.dat;http://cernvm-wpad.cern.ch/wpad.dat"' > /etc/cvmfs/default.local
#
RUN yum -y remove condor
RUN yum -y install https://linuxsoft.cern.ch/wlcg/centos7/x86_64/wlcg-repo-1.0.0-1.el7.noarch.rpm
COPY UMD-4-updates.repo /etc/yum.repos.d/UMD-4-updates.repo
RUN yum -y install blahp --disablerepo=* --enablerepo=UMD-4-updates
RUN yum -y install condor
#
RUN mkdir -p /cvmfs
RUN echo "alias htc='source cygno_htc'" >> /etc/bashrc 
RUN echo "alias activatedigt='source /cvmfs/sft.cygno.cloud.infn.it/config/setup_digi.sh'" >> /etc/bashrc
#
