# FROM dodasts/cygno-lab:<latest release> -> for example:
# FROM dodasts/cygno-lab:v1.0.16-cygno
FROM gmazzitelli/cygno-lab:v1.0.20-cygno

RUN yum remove -y oidc-agent oidc-agent-cli oidc-agent-desktop liboidc-agent4

ADD $PWD/rpm/  /rpm/
RUN rpm -i /rpm/* 
RUN yum install -y vim
