FROM harbor.cloud.infn.it/datacloud-templates/cygno-lab:cygno-minio-rgw
ARG TAG
#FROM gmazzitelli/${TAG}
ARG CLIB
RUN pip3 install --no-cache-dir -U git+https://github.com/CYGNUS-RD/cygno.git@${CLIB}
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt
RUN yum install -y https://research.cs.wisc.edu/htcondor/repo/10.x/el7/x86_64/release/htcondor-release-10.x-1.el7.noarch.rpm
RUN yum install -y condor
RUN yum install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
RUN yum install -y cvmfs
RUN mkdir -p /cvmfs/
RUN echo "alias htc='source cygno_htc'" >> /etc/bashrc 
