ARG TAG
FROM gmazzitelli/${TAG}
ARG CLIB
RUN pip3 install --no-cache-dir -U git+https://github.com/CYGNUS-RD/cygno.git@${CLIB}
COPY requirements.txt /tmp/requirements.txt
RUN pip3 install -r /tmp/requirements.txt
